version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"

  wordpress:
    image: wordpress:4
    ports:
      - "8080:80"
      - "8787:443" 
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_PASSWORD=1234
    links:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - /root/composetest/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
  nginx:
    image: nginx
    ports:
      - "7575:80"
    volumes:
      - /root/composetest/univers:/usr/share/nginx/html
